Resolve querystring
spoqa/nirum-python-wsgi pull request #5
Opened 2017-12-09 15:15 UTC by admire93

https://github.com/spoqa/nirum/issues/130

Resolve querystring when mapping service method to URL.

2017-12-09 17:01 UTC, dahlia requested changes
Build was failed.

2017-12-09 17:01 UTC, dahlia commented on nirum_wsgi.py
>              ))
As it's getting more complex, it would be better if we define a named tuple for this.

2017-12-09 17:01 UTC, dahlia commented on nirum_wsgi.py
> +    request_rules = sorted(rules, key=lambda x: x[1].names, reverse=True)
👍

2017-12-09 17:01 UTC, dahlia commented on nirum_wsgi.py
> +            if (request_method == verb or request_method == 'OPTIONS') and \
This expression can be simpler: `request_method in (verb, 'OPTIONS')`.

2017-12-09 17:01 UTC, dahlia commented on nirum_wsgi.py
> +        """Route HTTP request to Nirum service method.
How about adjusting this docstring to the following sentence?

> Route an HTTP request to a corresponding service method, or respond with an error status code if it found nothing.

2017-12-09 17:01 UTC, dahlia commented on nirum_wsgi.py
> +        :param environ: WSGI environment value.
“WSGI environment *dictionary*” is more accurate than just a “*value*.”

2017-12-09 17:01 UTC, dahlia commented on nirum_wsgi.py
> +        :param start_response: The function can start HTTP response.
As the meaning of `start_response` is quite clear in terms of WSGI, we can merely describe this as “a WSGI `start_response` callable” here.

2017-12-09 17:01 UTC, dahlia commented on nirum_wsgi.py
> +        # before searching for match results.
Some suggestions (*italics* are edits):

> Nirum compiler *appends an underscore to* the end of *the given `variable_name` if it's a reserved keyword by Python (e.g. `from` → `from_`, `def` → `def_`).*
>
> So *we need* to remove *a trailing underscore* from the `variable_name` *(if it has one)* before *looking up* match results.

Note that `int` is not a reserved keyword but a built-in function, Nirum compiler doesn't append `_` to `int`.

2017-12-09 17:01 UTC, dahlia commented on nirum_wsgi.py
> +                values.append(value)
It can be simpler if we use list comprehensions:

```python
values = [value for name, value in self.result if name == variable_name]
```

2017-12-09 17:01 UTC, dahlia commented on nirum_wsgi.py
> +    VALUE_PATTERN = re.compile('\{([a-zA-Z0-9_-]+)\}')
For regex patterns, raw string literals are encouraged.

2017-12-09 17:01 UTC, dahlia commented on nirum_wsgi.py
> +    VALUE_PATTERN = re.compile('\{([a-zA-Z0-9_-]+)\}')
Is it a pattern of *values*?  Not *variables*?

2018-01-04 13:40 UTC, dahlia approved these changes

2018-01-04 16:14 UTC, dahlia requested changes

2018-01-04 16:14 UTC, dahlia commented on CHANGES.rst
> +  [`#130`__]
```
CHANGES.rst:: (ERROR/3) Anonymous hyperlink mismatch: 2 references but 1 targets.
See "backrefs" attribute for IDs.
Exiting due to level-3 (ERROR) system message.
```

2018-01-08 11:05 UTC, admire93 commented
@dahlia i correct RST syntax  in `CHANGES.rst`.

2018-01-08 11:11 UTC, dahlia approved these changes

2018-01-08 11:12 UTC, merged